services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5671:5671
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping", "-q"]
      interval: 5s
      timeout: 2s
      retries: 5

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 1s
      retries: 3

  api-gateway-svc:
    build:
      context: .
      dockerfile: ./apps/api-gateway-svc/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      rabbitmq:
        condition: service_healthy

  user-svc:
    build:
      context: .
      dockerfile: ./apps/user-svc/Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data: