services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5671:5671
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping", "-q"]
      interval: 5s
      timeout: 2s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - /var/lib/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 1s
      retries: 3 

  api-gateway-svc:
    build:
      context: .
      dockerfile: ./apps/api-gateway-svc/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./apps/api-gateway-svc/.env

  user-svc:
    build:
      context: .
      dockerfile: ./apps/user-svc/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - ./apps/user-svc/.env

  notification-scheduler-svc:
    build:
      context: .
      dockerfile: ./apps/notification-scheduler-svc/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - ./apps/notification-scheduler-svc/.env

volumes:
  postgres_data: